version: '3.1'

services:
  db:
    image: postgres:10.12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: roov
      POSTGRES_USER: roov
      POSTGRES_DB: roov
    volumes:
      - ./initdb/roov.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: 
      context: .
      dockerfile: dev.dockerfile
    restart: always
    depends_on:
      - db
    environment:
      PORT: :3000
      DB_DRIVER: pgx
      DB_HOST: db
      DB_USER: roov
      DB_PASSWORD: roov
      DB_NAME: roov
    ports:
      - 3000:3000
    volumes:
      - ./:/app
